/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionDSLStandaloneSetup extends ExpressionDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
