/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class ExpressionDSLRuntimeModule extends AbstractExpressionDSLRuntimeModule {
}
