/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl.tests

import com.google.inject.Inject
import org.eclipse.xtext.testing.InjectWith
import org.eclipse.xtext.testing.extensions.InjectionExtension
import org.eclipse.xtext.testing.util.ParseHelper
import org.junit.jupiter.api.Assertions
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.^extension.ExtendWith

import org.xtext.example.expressiondsl.expressionDSL.FunctionDef
import org.xtext.example.expressiondsl.expressionDSL.IntConstant
import org.xtext.example.expressiondsl.expressionDSL.Model
import org.xtext.example.expressiondsl.expressionDSL.QualifiedRef
import org.xtext.example.expressiondsl.expressionDSL.StructDef
import org.xtext.example.expressiondsl.expressionDSL.SubFieldDef
import org.xtext.example.expressiondsl.expressionDSL.VariableArrayOrFunctionRef
import org.xtext.example.expressiondsl.expressionDSL.VariableAssignment
import org.xtext.example.expressiondsl.expressionDSL.VariableDef

//import static extension org.junit.Assertions.*

@ExtendWith(InjectionExtension)
@InjectWith(ExpressionDSLInjectorProvider)
class ExpressionDSLParsingTest01 {
	@Inject
	ParseHelper<Model> parseHelper

	@Test
	def void test01() {
	
		var String actualPrecedence = null

		val result = parseHelper.parse('''
			var int intA;
			var int intB dim(10);

			struct structA;
				subf int subfA;
			endstruct;

			struct structB dim(10);
				subf int subfB;
			endstruct;

			struct structC dim(10);
				subf int subfC dim(20);
				struct subStructC dim(30);
					subf int subSubfC dim(40);
				endstruct;
			endstruct;

			def char funcTest;

			// Normal Assignment
			intA = intB;

			// Assign result of function
			intA = funcTest();
			intA = funcTest(1); 
			intA = funcTest(2:3);
			intA = funcTest(intA);

			// Arrays
			intA = intB(4);
			intA = intB(funcTest(5));
			intA = intB(intA);

			// Qualified
			intA = structA;
			intA = structA.subfA;

			intA = structB(5);
			intA = structB(funcTest());

			intA = structB(6).subfB;

			intA = structC(7).subfC(8);
			intA = structC(9).subStructC(10).subSubfC(11);

		''')
		Assertions.assertNotNull(result)
		val errors = result.eResource.errors
//		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')

//		var int intA;
		var intA = result.statements.get(0) as VariableDef;
		Assertions.assertEquals('intA', intA.name)
		
//		var int intB dim(10);
		var intB = result.statements.get(1) as VariableDef;
		Assertions.assertEquals('intB', intB.name)

//		struct structA;
//			subf int subfA;
//		endstruct;
		var structA = result.statements.get(2) as StructDef;
		var subfA = structA.subFields.get(0) as SubFieldDef;
		Assertions.assertEquals('structA', structA.name)
		Assertions.assertEquals('subfA', subfA.name)

//		struct structB dim(10);
//			subf int subfB;
//		endstruct;
		var structB = result.statements.get(3) as StructDef;
		var subfB = structB.subFields.get(0) as SubFieldDef;
		Assertions.assertEquals('structB', structB.name)
		Assertions.assertEquals('subfB', subfB.name)

//		struct structC dim(10);
//			subf int subfC dim(20);
//			struct subStructC dim(30);
//				subf int subSubfC dim(40);
//			endstruct;
//		endstruct;
		var structC = result.statements.get(4) as StructDef;
		var subfC = structC.subFields.get(0) as SubFieldDef;
		var subStructC = structC.subFields.get(1) as StructDef;
		var subSubfC = subStructC.subFields.get(0) as SubFieldDef;
		Assertions.assertEquals('structC', structC.name)
		Assertions.assertEquals('subfC', subfC.name)
		Assertions.assertEquals('subStructC', subStructC.name)
		Assertions.assertEquals('subSubfC', subSubfC.name)

//		def char funcTest;
		var funcTest = result.statements.get(5) as FunctionDef;
		Assertions.assertEquals('funcTest', funcTest.name)

//		intA = intB;
		var VarAssignment01 = result.statements.get(6) as VariableAssignment;
		var tgtvar01 = VarAssignment01.tgtvar as VariableDef;		
		var exp01 = VarAssignment01.exp as VariableArrayOrFunctionRef;
		var ref01 = exp01.ref as VariableDef;
		Assertions.assertEquals('intA', tgtvar01.name)
		Assertions.assertEquals('intB', ref01.name)
		actualPrecedence = TestUtils.stringRepr(exp01)
		Assertions.assertEquals('intB', actualPrecedence)

//		intA = funcTest();
		var VarAssignment02 = result.statements.get(7) as VariableAssignment;
		var tgtvar02 = VarAssignment02.tgtvar as VariableDef;
		var exp02 = VarAssignment02.exp as VariableArrayOrFunctionRef;
		var ref02 = exp02.ref as FunctionDef;
		Assertions.assertEquals('intA', tgtvar02.name)
		Assertions.assertEquals('funcTest', ref02.name)
		actualPrecedence = TestUtils.stringRepr(exp02)
		Assertions.assertEquals('funcTest()', actualPrecedence)

//		intA = funcTest(1);
		var VarAssignment03 = result.statements.get(8) as VariableAssignment;
		var tgtvar03 = VarAssignment03.tgtvar as VariableDef;
		var exp03 = VarAssignment03.exp as VariableArrayOrFunctionRef;
		var ref03 = exp03.ref as FunctionDef;
		var args03A = exp03.args.head as IntConstant
		Assertions.assertEquals('intA', tgtvar03.name)
		Assertions.assertEquals('funcTest', ref03.name)
		Assertions.assertEquals(1, exp03.args.length)
		Assertions.assertEquals(1, args03A.value)
		actualPrecedence = TestUtils.stringRepr(exp03)
		Assertions.assertEquals('funcTest(1)', actualPrecedence)

//		intA = funcTest(2:3);
		var VarAssignment04 = result.statements.get(9) as VariableAssignment;
		var tgtvar04 = VarAssignment04.tgtvar as VariableDef;
		var exp04 = VarAssignment04.exp as VariableArrayOrFunctionRef;
		var ref04 = exp04.ref as FunctionDef;
		var args04A = exp04.args.get(0) as IntConstant
		var args04B = exp04.args.get(1) as IntConstant
		Assertions.assertEquals('intA', tgtvar04.name)
		Assertions.assertEquals('funcTest', ref04.name)
		Assertions.assertEquals(2, exp04.args.length)
		Assertions.assertEquals(2, args04A.value)
		Assertions.assertEquals(3, args04B.value)
		actualPrecedence = TestUtils.stringRepr(exp04)
		Assertions.assertEquals('funcTest(2:3)', actualPrecedence)

//		intA = funcTest(intA);
		var VarAssignment08 = result.statements.get(10) as VariableAssignment;
		var tgtvar08 = VarAssignment08.tgtvar as VariableDef; //intA
		var exp08 = VarAssignment08.exp as VariableArrayOrFunctionRef; //funcTest(intA)
		var ref08 = exp08.ref as FunctionDef // funcTest
		var args08A = exp08.args.get(0) as VariableArrayOrFunctionRef // intA
		var ref09 = args08A.ref as VariableDef;
		Assertions.assertEquals('intA', tgtvar08.name)
		Assertions.assertEquals('funcTest', ref08.name)
		Assertions.assertEquals(1, exp08.args.length)
		Assertions.assertEquals('intA', ref09.name)
		actualPrecedence = TestUtils.stringRepr(exp08)
		Assertions.assertEquals('funcTest(intA)', actualPrecedence)

//		intA = intB(4);
		var VarAssignment05 = result.statements.get(11) as VariableAssignment;
		var tgtvar05 = VarAssignment05.tgtvar as VariableDef;
		var exp05 = VarAssignment05.exp as VariableArrayOrFunctionRef;
		var ref05 = exp05.ref as VariableDef;
		var parm05A = exp05.args.get(0) as IntConstant
		Assertions.assertEquals('intA', tgtvar05.name)
		Assertions.assertEquals('intB', ref05.name)
		Assertions.assertEquals(1, exp05.args.length)
		Assertions.assertEquals(4, parm05A.value)
		actualPrecedence = TestUtils.stringRepr(exp05)
		Assertions.assertEquals('intB(4)', actualPrecedence)

//		intA = intB(funcTest(5));
		var VarAssignment06 = result.statements.get(12) as VariableAssignment;
		var tgtvar06 = VarAssignment06.tgtvar as VariableDef; //intA
		var exp06 = VarAssignment06.exp as VariableArrayOrFunctionRef; //intB(funcTest(5))
		var ref06 = exp06.ref as VariableDef; //intB
		var parm06A = exp06.args.get(0) as VariableArrayOrFunctionRef // funcTest(5)
		var ref07 = parm06A.ref as FunctionDef // funcTest
		var param07A = parm06A.args.get(0) as IntConstant
		Assertions.assertEquals('intA', tgtvar06.name)
		Assertions.assertEquals('intB', ref06.name)
		Assertions.assertEquals(1, exp06.args.length)
		Assertions.assertEquals('funcTest', ref07.name)
		Assertions.assertEquals(1, parm06A.args.length)
		Assertions.assertEquals(5, param07A.value)
		actualPrecedence = TestUtils.stringRepr(exp06)
		Assertions.assertEquals('intB(funcTest(5))', actualPrecedence)

//		intA = intB(intA);
		var VarAssignment10 = result.statements.get(13) as VariableAssignment;
		var tgtvar10 = VarAssignment10.tgtvar as VariableDef; //intA
		var exp10 = VarAssignment10.exp as VariableArrayOrFunctionRef; //intB(intA)
		var ref10 = exp10.ref as VariableDef // intB
		var parm10A = exp10.args.get(0) as VariableArrayOrFunctionRef // intA
		var ref11 = parm10A.ref as VariableDef;
		Assertions.assertEquals('intA', tgtvar10.name)
		Assertions.assertEquals('intB', ref10.name)
		Assertions.assertEquals(1, exp10.args.length)
		Assertions.assertEquals('intA', ref11.name)

//		intA = structA;
		var VarAssignment12 = result.statements.get(14) as VariableAssignment;
		var tgtvar12 = VarAssignment12.tgtvar as VariableDef;
		var exp12 = VarAssignment12.exp as VariableArrayOrFunctionRef;
		var ref12 = exp12.ref as StructDef;
		Assertions.assertEquals('intA', tgtvar12.name)
		Assertions.assertEquals('structA', ref12.name)

//		intA = structA.subfA;
		var VarAssignment13 = result.statements.get(15) as VariableAssignment;
		var tgtvar13 = VarAssignment13.tgtvar as VariableDef;
		var exp13 = VarAssignment13.exp as QualifiedRef;
		var head13 = exp13.head as VariableArrayOrFunctionRef;
		var head13ref = head13.ref as StructDef
		var tail13 = exp13.tail as VariableArrayOrFunctionRef;
		var tail13ref = tail13.ref as SubFieldDef // <<< Can't Cast Named to SubFieldDef <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
		Assertions.assertEquals('intA', tgtvar13.name)
		Assertions.assertEquals('structA', head13ref.name)
//>>>	Assertions.assertEquals('subfA', tail13ref.name) <<<

//		intA = structB(5);
		var VarAssignment14 = result.statements.get(16) as VariableAssignment;
		var tgtvar14 = VarAssignment14.tgtvar as VariableDef;
		var exp14 = VarAssignment14.exp as VariableArrayOrFunctionRef;
		var ref14 = exp14.ref as StructDef;
		var param14A = exp14.args.get(0) as IntConstant
		Assertions.assertEquals('intA', tgtvar14.name)
		Assertions.assertEquals('structB', ref14.name)
		Assertions.assertEquals(1, exp14.args.length)
		Assertions.assertEquals(5, param14A.value)

//		intA = structB(funcTest());
		var VarAssignment15 = result.statements.get(17) as VariableAssignment;
		var tgtvar15 = VarAssignment15.tgtvar as VariableDef;
		var exp15 = VarAssignment15.exp as VariableArrayOrFunctionRef;
		var ref15 = exp15.ref as StructDef;
		var param15A = exp15.args.get(0) as VariableArrayOrFunctionRef
		var param15Aref = param15A.ref as FunctionDef
		Assertions.assertEquals('intA', tgtvar15.name)
		Assertions.assertEquals('structB', ref15.name)
		Assertions.assertEquals(1, exp15.args.length)
		Assertions.assertEquals('funcTest', param15Aref.name)

//		intA = structB(6).subfB;
		var VarAssignment16 = result.statements.get(18) as VariableAssignment;
		var tgtvar16 = VarAssignment16.tgtvar as VariableDef;
		var exp16 = VarAssignment16.exp as QualifiedRef;
		var head16 = exp16.head as VariableArrayOrFunctionRef;
		var head16ref = head16.ref as StructDef
		var head16paramA = head16.args.get(0) as IntConstant
		var tail16 = exp16.tail as VariableArrayOrFunctionRef;
//>>>	var tail16ref = tail16.ref as SubFieldDef; <<<
		Assertions.assertEquals('intA', tgtvar16.name)
		Assertions.assertEquals('structB', head16ref.name)
		Assertions.assertEquals(1, head16.args.length)
		Assertions.assertEquals(6, head16paramA.value)
//>>>	Assertions.assertEquals('subfB', tail16ref.name) <<<

//		intA = structC(7).subfC(8);
		var VarAssignment17 = result.statements.get(19) as VariableAssignment;
		var tgtvar17 = VarAssignment17.tgtvar as VariableDef;
		var exp17 = VarAssignment17.exp as QualifiedRef;
		var head17 = exp17.head as VariableArrayOrFunctionRef;
		var head17ref = head17.ref as StructDef
		var head17paramA = head17.args.get(0) as IntConstant
		var tail17 = exp17.tail as VariableArrayOrFunctionRef;
//>>>	var tail17ref = tail17.ref as SubFieldDef <<<
		var tail17paramA = tail17.args.get(0) as IntConstant
		Assertions.assertEquals('intA', tgtvar17.name)
		Assertions.assertEquals('structC', head17ref.name)
		Assertions.assertEquals(1, head17.args.length)
		Assertions.assertEquals(7, head17paramA.value)
//>>>	Assertions.assertEquals('subfC', tail17ref.name) <<<
		Assertions.assertEquals(1, tail17.args.length)
		Assertions.assertEquals(8, tail17paramA.value)

//		intA = structC(9).subStructC(10).subSubfC(11);
		var VarAssignment18 = result.statements.get(20) as VariableAssignment
		var tgtvar18 = VarAssignment18.tgtvar as VariableDef //intA
		var exp18 = VarAssignment18.exp as QualifiedRef // structC(9).subStructC(10).subSubfC(11);
		
		var head18 = exp18.head as QualifiedRef
		var head18head18 = head18.head as VariableArrayOrFunctionRef
		var head18head18ref = head18head18.ref as StructDef //structC
		var head18head18paramA = head18head18.args.get(0) as IntConstant //(9)

		var tail18 = exp18.tail as VariableArrayOrFunctionRef
//		var tail18ref = tail18.ref as StructDef //subStructC <<<
		var tail18paramA = tail18.args.get(0) as IntConstant //(10)
//		var tail18 = exp18.tail as QualifiedRef; // subStructC(10).subSubfC(11);		
//		var head18ref = head18.ref as StructDef 
//		var tail18head18ref = tail18head18.ref as StructDef //structC
//		var tail18head18paramA = tail18head18.args.get(0) as IntConstant //(10)
//		
////		var tail18paramA = tail18.args.get(0) as IntConstant
//
////		//TODO 'subSubfC'
////		//TODO 11 from subSubfC(11)

		Assertions.assertEquals('intA', tgtvar18.name)
		Assertions.assertEquals('structC', head18head18ref.name)
		Assertions.assertEquals(1, head18head18.args.length)
		Assertions.assertEquals(9, head18head18paramA.value)
//>>>	AssertEquals('subStructC', tailref.name)
		Assertions.assertEquals(1, tail18.args.length)
//		Assertions.assertEquals(10, tail18paramA.value)
////		AssertEquals('subSubfC', .name) <<<
////		Assertions.assertEquals(1, .args.length)
////		Assertions.assertEquals(11, .value)

		Assertions.assertTrue(errors.isEmpty, '''Unexpected errors: «errors.join(", ")»''')
	}

}