/*
 * generated by Xtext 2.16.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl.ide


/**
 * Use this class to register ide components.
 */
class ExpressionDSLIdeModule extends AbstractExpressionDSLIdeModule {
}
