/*
 * generated by Xtext 2.14.0
 */
package org.xtext.example.expressiondsl.ide


/**
 * Use this class to register ide components.
 */
class ExpressionDSLIdeModule extends AbstractExpressionDSLIdeModule {
}
