/*
 * generated by Xtext 2.15.0-SNAPSHOT
 */
package org.xtext.example.expressiondsl.web


/**
 * Use this class to register additional components to be used within the web application.
 */
class ExpressionDSLWebModule extends AbstractExpressionDSLWebModule {
}
